management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path: "/"
      path-mapping:
        prometheus: "metrics"

spring:
  autoconfigure:
    exclude:
      # Disable UserDetailsServiceAutoConfiguration to prevent auto-creation of a test user
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Ensure OpenAPI docs display correct URL when server is behind a proxy
server:
  use-forwarded-headers: true
  forward-headers-strategy: framework
  error:
    include-stacktrace: never

build:
  version: "@project.version@"
